### ISSUE TITLE
Raspberry pi bluetooth work pls

### ISSUE THREAD

**Issue by tallpants** [EnKrypt/Magnus#2]
So far :
* Flashed wrong version of Raspbian
* Connection refused
* Flashed Raspbian again.
* No VNC
* Flashed full version of Raspbian
* Compiled 3 different versions of bluez
* Operation not permitted
* bluetoothd not running
* No agent registered
* Input/Output Error
* Permission Denied
* RSSI = -256
* Switched from Bash to Ruby
* Switched Ruby to Bash
* Switched Bash to Python
* ascii not in ordinal range

**Comment by rohinrohin** [comment]
bro is now work. kindly take chill. I push soon.

**Comment by tallpants** [comment]
:rainbow:
